config/routes.rb
Myapp::Application.routes.draw do

  resources :accounts
  resources :plans
  get 'static_pages/index'

  get 'steps/first'

  get 'steps/second'

  get 'steps/third'

  get 'steps/fourth'

  get 'steps/finish'

  resources :events
  resources :receipes
  resources :apportionment_per_greenhouses
  resources :user_roles
  resources :permissions
  resources :roles
  resources :role_permissions
  resources :user_companies
  resources :cycles
  resources :companies
  
  get 'reports/index'

  get 'reports/quick_general_status'

  resources :unit_conversions
  resources :unit_types
  resources :selections
  resources :product_varieties
  resources :product_presentations
  resources :product_qualities
  resources :selection_items
  resources :sales
  resources :sale_items
  resources :products
  resources :harvests
  resources :weathers
  resources :environments
  resources :environmental_conditions
  resources :phenological_stages
  resources :leachates
  resources :suppliers
  resources :product_application_buys
  resources :administration_costs
  resources :operating_costs
  resources :fertigations
  resources :fertigation_items
  resources :application_products
  resources :application_items
  resources :applications
  resources :application_processes
  resources :greenhouse_employees

  resources :pay_roll_items do
    put :update_discount
    put :update_bonus
  end

  resources :pay_rolls

  resources :assistances

  resources :job_positions

  resources :greenhouses

  resources :employees

  get "home/index"
  get "home/minor"

  devise_for :users, controllers: { registrations: "users/registrations", 
                                    sessions: "users/sessions" }

  devise_scope :user do 
    get "users_list" => "manage_users#index"
    get "edit_user" => "manage_users#edit_user"
    get "new_user" => "manage_users#new_user"
    post "create_user" => "manage_users#create_user"
    post "update_user" => "manage_users#update_user"
    get "show_user" => "manage_users#show_user"
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

root to: 'static_pages#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
	belongs_to :greenhouse
	belongs_to :application_process
	has_many :application_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :check_if_allowed_controller, if: :user_signed_in?
  before_action :check_if_allowed_action, if: :user_signed_in?
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_user_plan, if: :user_signed_in?


  helper_method :is_allowed?


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected

  	def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :second_lat_name, :account_id])
  	end

    def check_if_allowed_controller
      if is_allowed?(params[:controller]) != true
        redirect_to root_path, notice: (t :not_enough_permissions)
      end
    end

    def check_if_allowed_action
      ### Debugging line ###
      puts "checking.....  controller = #{params[:controller]}, action = #{params[:action]}, #{params[:controller]}/#{params[:action]}"
      if is_allowed?("#{params[:controller]}/#{params[:action]}") != true
       redirect_to root_path, notice: (t :not_enough_permissions)
      end
    end

  	def is_allowed?(permission)
  		if user_signed_in?
  			current_user.roles.each do |user_role|
  			  user_role.permissions.each do |user_permission|
  			    if user_permission.value == permission
  			      return true
  			    end
  			  end
  			end
  		else
  			return false
  		end
  	end

    def after_sign_in_path_for(resource)
        if resource.is_a?(User) && resource.account.plan.nil?
          '/steps/first'
        else
          super
        end
    end

    # The path used after sign up for inactive accounts.
    #def after_inactive_sign_up_path_for(resource)
    #  puts "Im inside after_inactive_sign_up_path_for"
    #  companies_path
    #end

    # The path used after sign up.
    #def after_sign_up_path_for(resource)
    #  companies_path
    #end

    def check_user_plan
      if current_user.account.plan.nil?
        redirect_to '/steps/first'
      end
    end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :update_application_product_destroy, only: [:destroy]

  # GET /applications
  # GET /applications.json
  def index
    if params[:search]
      company_id = params[:search][:company_id]
      greenhouse_id = params[:search][:greenhouse_id]
      @show_applications = true
      @greenhouse = Greenhouse.find(greenhouse_id)
      @cycle = Cycle.where(greenhouse_id: greenhouse_id).active.first
      from_date = @cycle.start_date
      to_date = @cycle.end_date
      @applications = Application.where(greenhouse_id: greenhouse_id).where(application_date: from_date..to_date).order(:application_date)
      @application = Application.new
    else
      @show_applications == false
      @companies = current_user.companies
      @greenhouses = Greenhouse.where(company_id: @companies.first.id..@companies.last.id)
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application_item = ApplicationItem.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /applications/new
  def new
    @application = Application.new
    respond_to do |format|
      format.js
      format.html
      format.json
    end
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.js
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application }
      else
        format.html { render action: 'new' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.js
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:application_date, :application_process_id, :purpose, :greenhouse_id, 
                  :application_cost, :application_item_ids => [])
    end

    def update_application_product_destroy
      @application.application_items.each do |application_item|
        application_product = @application_item.application_product
        unit_type = application_item.unit_type
        quantity = application_item.total_product_used
        converted_quantity = unit_type.convert_to(quantity, application_product.unit_type.abbreviation)
        application_product.quantity_available += converted_quantity
        application_product.save

        # Now update the total_cost
        application_product.total_cost = application_product.unit_cost * application_product.quantity_available
        application_product.save
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_application.html.erb
      <tr id="application_<%= application.id %>">
        <td><%= application.application_date %></td>
        <td><%= application.application_process.name %></td>
        <td><%= application.purpose %></td>
        <td><%= application.greenhouse.name %></td>
        <td>
          <% application.application_items.each do |application_item| %>
            <%= application_item.application_product.name unless application_item.application_product.nil? %><br>
          <% end %>
        </td>
        <td class="alnright"><%= number_to_currency(application.application_cost, precision: 2) %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Destroy', application, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/applications/_application_item.html.erb
		<tr id="application_item_<%= application_item.id %>">
          <td><%= application_item.application_product.name unless application_item.application_product.nil? %></td>
          <td><%= application_item.unit_type.name unless application_item.unit_type.nil? %></td>
          <td class="alnright"><%= number_with_precision(application_item.quantity, precision: 2, delimiter: ',') %></td>
          <td class="alnright"><%= number_with_precision(application_item.h2o_quantity_liters, precision: 2, delimiter: ',') %></td>
          <td class="alnright"><%= number_with_precision(application_item.total_product_used, precision: 2, delimiter: ',') %> <%= application_item.application_product.unit_type.abbreviation unless application_item.application_product.nil? %></td>
          <td class="alnright"><%= number_to_currency(application_item.cost_per_unit, precision: 2, delimiter: ',') %></td>
          <td class="alnright"><%= number_to_currency(application_item.total_cost, precision: 2, delimiter: ',') %></td>
          <td><%= link_to 'Destroy', application_item, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
        </tr>

app/views/applications/_form.html.erb
<%= simple_form_for(@application) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :application_date %>
    <%= f.association :application_process %>
    <%= f.input :purpose %>
    <%= f.association :greenhouse %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/applications/create.js.erb
//alert('I was called');
$("<%= escape_javascript(render @application) %>").appendTo("#applications").effect("highlight", {color: '#00DCB7'}, 2000);
$('#new_application_form')[0].reset();

app/views/applications/destroy.js.erb
//alert('Hola');
$('#<%= dom_id(@application) %>').effect("highlight", {color: '#00DCB7'}, 800).fadeOut();

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
  <p id="notice"><%= notice %></p>

<% if @show_applications == true  %>
  <h1>Listing Applications</h1>

  <div class="table-responsive">
    <table class="table table-hover dataTable table-striped table-bordered">
      <thead>
        <tr>
          <th>Application date</th>
          <th>Application process</th>
          <th>Purpose</th>
          <th>Greenhouse</th>
          <th>Application items</th>
          <th>Application cost</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody id="applications">
        <% @applications.each do |application| %>
          <%= render "application", :application => application %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-8">
    <br>
    <strong>Total:</strong>
    <div id="operating_cost_total"><strong><%= number_to_currency(@applications.sum(:application_cost), precision: 2) %></strong></div>
    <br><br>
  </div>

  <br>

  <div class="col-md-8">
    <%= link_to 'New Application', new_application_path, remote: true, id: 'new_application_link' %>
  </div>

  <div class="col-md-5" id="div_new_application_form">
    <%= simple_form_for(@application, remote: true, html: { id: 'new_application_form' }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= f.association :greenhouse, :as => :hidden, input_html: { value: @greenhouse.id } %>
        <%= f.input :application_date %>
        <%= f.association :application_process %>
        <%= f.input :purpose %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, remote: true, id: 'new_application_submit_button' %>
      </div>
    <% end %>
  </div>

<% else %>
  <div class="col-md-2">
    <%= simple_form_for :search, url: applications_path, :method => :get do |f| %>
        <%= f.input :company_id, collection: @companies, label_method: :name, value_method: :id, placeholder: 'Select the company' %>
        <%= f.input :greenhouse_id, collection: @greenhouses, label_method: :name, value_method: :id, placeholder: 'Select the company' %>
        <%= f.submit 'Generar', class: 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/new.js.erb
$('#new_application_link').hide().after('');

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-8">
  <div class="col-md-4">
    <strong>Application date:</strong>
    <%= @application.application_date %>
    <br>
  </div>

  <div class="col-md-4">
    <strong>Application process:</strong>
    <%= @application.application_process.name %>
    <br>
  </div>
</div>

<div class="col-md-8">
  <div class="col-md-4">
    <strong>Greenhouse:</strong>
    <%= @application.greenhouse.name %>
    <br>
  </div>

  <div class="col-md-4">
    <strong>Purpose:</strong>
    <%= @application.purpose %>
    <br>
  </div>
</div>



<div class="col-md-8">
  <br>
  <br>
  <div class="table-responsive">
    <table  class="table table-hover dataTable table-striped table-bordered">
      <thead>
        <tr>
          <th>Application product</th>
          <th>Unit of measure</th>
          <th>Quantity per L of water</th>
          <th>Liters of water</th>
          <th>Total product used</th>
          <th>Cost per unit</th>
          <th>Total cost</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody id="application_items">
        <% @application.application_items.each do |application_item| %>
          <%= render 'application_item', :application_item => application_item %>
        <% end %>
      </tbody>
    </table>
  </div>


  <%= link_to 'New Application item', new_application_item_path, remote: true, id: 'new_application_item_link' %>

  <div class="col-md-8" id="div_new_application_item_form">
    <%= simple_form_for(@application_item, remote: true, html: { id: 'application_item_form' }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= f.association :application, :as => :hidden, input_html: { value: @application.id } %>
        <%= f.association :application_product, collection: ApplicationProduct.where("quantity_available > ?", 0).order(:name), :label_method => :name_quantity_available, value_method: :id %>
        <%= f.association :unit_type %>
        <%= f.input :quantity, label: 'gr or ml per L of water' %>
        <%= f.input :h2o_quantity_liters, label: 'Water quantity' %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, id: 'new_application_item_submit_button' %>
      </div>
    <% end %>
  </div>

</div>

<div class="col-md-8">
<br>
<br>
<br>
  <strong>Application cost:</strong>
  <div id="application_cost"><%= number_to_currency(@application.application_cost, precision: 2) %></div>
  <br>
</div>

<div class="col-md-8">
<br>
  <%= link_to 'Edit', edit_application_path(@application) %> |
  <%= link_to 'Back', applications_path %>
</div>