config/routes.rb
Myapp::Application.routes.draw do

  resources :accounts
  resources :plans
  get 'static_pages/index'

  get 'steps/first'

  get 'steps/second'

  get 'steps/third'

  get 'steps/fourth'

  get 'steps/finish'

  resources :events
  resources :receipes
  resources :apportionment_per_greenhouses
  resources :user_roles
  resources :permissions
  resources :roles
  resources :role_permissions
  resources :user_companies
  resources :cycles
  resources :companies
  
  get 'reports/index'

  get 'reports/quick_general_status'

  resources :unit_conversions
  resources :unit_types
  resources :selections
  resources :product_varieties
  resources :product_presentations
  resources :product_qualities
  resources :selection_items
  resources :sales
  resources :sale_items
  resources :products
  resources :harvests
  resources :weathers
  resources :environments
  resources :environmental_conditions
  resources :phenological_stages
  resources :leachates
  resources :suppliers
  resources :product_application_buys
  resources :administration_costs
  resources :operating_costs
  resources :fertigations
  resources :fertigation_items
  resources :application_products
  resources :application_items
  resources :applications
  resources :application_processes
  resources :greenhouse_employees

  resources :pay_roll_items do
    put :update_discount
    put :update_bonus
  end

  resources :pay_rolls

  resources :assistances

  resources :job_positions

  resources :greenhouses

  resources :employees

  get "home/index"
  get "home/minor"

  devise_for :users, controllers: { registrations: "users/registrations", 
                                    sessions: "users/sessions" }

  devise_scope :user do 
    get "users_list" => "manage_users#index"
    get "edit_user" => "manage_users#edit_user"
    get "new_user" => "manage_users#new_user"
    post "create_user" => "manage_users#create_user"
    post "update_user" => "manage_users#update_user"
    get "show_user" => "manage_users#show_user"
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

root to: 'static_pages#index'

end

app/models/application_product.rb
class ApplicationProduct < ActiveRecord::Base
	belongs_to :unit_type
	has_many :application_items, dependent: :nullify
	has_many :fertigation_items, dependent: :nullify
	has_many :product_application_buys, dependent: :nullify

	validates :name, :unit_type, presence: true
	validates :name, uniqueness: true

	def name_abbreviation
		"#{name} (#{unit_type.abbreviation})"
	end

	def name_quantity_available
		"#{name} (#{quantity_available} #{unit_type.abbreviation})"
	end
end

app/controllers/application_products_controller.rb
class ApplicationProductsController < ApplicationController
  before_action :set_application_product, only: [:show, :edit, :update, :destroy]
  before_action :set_to_ceros, only: [:create]

  # GET /application_products
  # GET /application_products.json
  def index
    @application_products = ApplicationProduct.all
    @application_product = ApplicationProduct.new
  end

  # GET /application_products/1
  # GET /application_products/1.json
  def show
  end

  # GET /application_products/new
  def new
    @application_product = ApplicationProduct.new
    respond_to do |format|
      format.js
      format.html
      format.json
    end
  end

  # GET /application_products/1/edit
  def edit
  end

  # POST /application_products
  # POST /application_products.json
  def create
    @application_product = ApplicationProduct.new(application_product_params)

    respond_to do |format|
      if @application_product.save
        format.js
        format.html { redirect_to @application_product, notice: 'Application product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application_product }
      else
        flash[:notice] = 'This is a test!'
        format.js
        format.html { render action: 'new' }
        format.json { render json: @application_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_products/1
  # PATCH/PUT /application_products/1.json
  def update
    respond_to do |format|
      if @application_product.update(application_product_params)
        format.html { redirect_to @application_product, notice: 'Application product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_products/1
  # DELETE /application_products/1.json
  def destroy
    @application_product.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to application_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_product
      @application_product = ApplicationProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_product_params
      params.require(:application_product).permit(:application_item_ids, :name, :description, :quantity_available, 
                            :units_of_measure, :unit_type_id, :total_cost, :unit_cost)
    end

    def set_to_ceros
      params[:application_product][:quantity_available] = 0.0
      params[:application_product][:unit_cost] = 0.0
      params[:application_product][:total_cost] = 0.0
    end
end

app/helpers/application_products_helper.rb
module ApplicationProductsHelper
end

app/views/application_products/_application_product.html.erb
	<tr id="application_product_<%= application_product.id %>">
      <td><%= application_product.name %></td>
      <td><%= application_product.description %></td>
      <td><%= application_product.unit_type.name unless application_product.unit_type.nil? %></td>
      <td><%= application_product.quantity_available %></td>
      <td><%= application_product.unit_cost %></td>
      <td><%= application_product.total_cost %></td>
      <td><%= link_to (t :show), application_product %></td>
      <td><%= link_to (t :destroy), application_product, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
    </tr>

app/views/application_products/_form.html.erb
<%= simple_form_for(@application_product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :quantity_available %>
    <%= f.association :unit_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/application_products/create.js.erb
//alert('I was called');
$("<%= escape_javascript(render @application_product) %>").appendTo("#application_products").effect("highlight", {color: '#00DCB7'}, 2000);
$('#application_products_form')[0].reset();

app/views/application_products/destroy.js.erb
//alert('Hola');
$('#<%= dom_id(@application_product) %>').effect("highlight", {color: '#00DCB7'}, 800).fadeOut();

app/views/application_products/edit.html.erb
<h1>Editing Application Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @application_product %> |
<%= link_to 'Back', application_products_path %>

app/views/application_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t :listing_application_products %></h1>

<div class="table-responsive">
  <table class="table table-hover dataTable table-striped table-bordered">
    <thead>
      <tr>
        <th><%=t :name %></th>
        <th><%=t :description %></th>
        <th><%=t :unit_of_measure %></th>
        <th><%=t :quantity_available %></th>
        <th><%=t :unit_cost %></th>
        <th><%=t :total_cost %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody id="application_products">
      <% @application_products.each do |application_product| %>
        <%= render "application_product", :application_product => application_product %>
      <% end %>
    </tbody> 
  </table>
</div>

<br>

<div id="div_application_products_form">
  <%= simple_form_for(@application_product, remote: true, html: { id: 'application_product_form' }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name, label: t(:name ) %>
      <%= f.input :description, label: t(:description ) %>
      <%= f.association :unit_type, label: t(:unit_of_measure ) %>
    </div>

    <div class="form-actions">
      <%= f.submit t(:create_new_product), id: 'new_application_product_submit_button', class: 'btn btn-default' %>
    </div>
  <% end %>
</div>


<br>

<%= link_to t(:add_product), new_application_product_path, remote: true, id: "new_application_product_link" %>

app/views/application_products/new.html.erb
<h1>New Application Product</h1>

<%= render 'form' %>

<%= link_to 'Back', application_products_path %>

app/views/application_products/new.js.erb
$('#new_application_product_link').hide().after('');

app/views/application_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application_product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @application_product.description %>
</p>

<p>
  <strong>Quantity available:</strong>
  <%= @application_product.quantity_available %>
</p>

<p>
  <strong>Units of measure:</strong>
  <%= @application_product.unit_type.name unless @application_product.unit_type.nil? %>
</p>

<%= link_to 'Edit', edit_application_product_path(@application_product) %> |
<%= link_to 'Back', application_products_path %>