config/routes.rb
Myapp::Application.routes.draw do

  resources :accounts
  resources :plans
  get 'static_pages/index'

  get 'steps/first'

  get 'steps/second'

  get 'steps/third'

  get 'steps/fourth'

  get 'steps/finish'

  resources :events
  resources :receipes
  resources :apportionment_per_greenhouses
  resources :user_roles
  resources :permissions
  resources :roles
  resources :role_permissions
  resources :user_companies
  resources :cycles
  resources :companies
  
  get 'reports/index'

  get 'reports/quick_general_status'

  resources :unit_conversions
  resources :unit_types
  resources :selections
  resources :product_varieties
  resources :product_presentations
  resources :product_qualities
  resources :selection_items
  resources :sales
  resources :sale_items
  resources :products
  resources :harvests
  resources :weathers
  resources :environments
  resources :environmental_conditions
  resources :phenological_stages
  resources :leachates
  resources :suppliers
  resources :product_application_buys
  resources :administration_costs
  resources :operating_costs
  resources :fertigations
  resources :fertigation_items
  resources :application_products
  resources :application_items
  resources :applications
  resources :application_processes
  resources :greenhouse_employees

  resources :pay_roll_items do
    put :update_discount
    put :update_bonus
  end

  resources :pay_rolls

  resources :assistances

  resources :job_positions

  resources :greenhouses

  resources :employees

  get "home/index"
  get "home/minor"

  devise_for :users, controllers: { registrations: "users/registrations", 
                                    sessions: "users/sessions" }

  devise_scope :user do 
    get "users_list" => "manage_users#index"
    get "edit_user" => "manage_users#edit_user"
    get "new_user" => "manage_users#new_user"
    post "create_user" => "manage_users#create_user"
    post "update_user" => "manage_users#update_user"
    get "show_user" => "manage_users#show_user"
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

root to: 'static_pages#index'

end

app/models/pay_roll_item.rb
class PayRollItem < ActiveRecord::Base
	belongs_to :pay_roll
	belongs_to :employee
	has_many :assistances, dependent: :nullify

	#validates_presence_of :discounts, on: :update_discount
	#validates :discounts, numericality: { greater_than: -1 }

	#validates_presence_of :bonuses, on: :update_bonus
	#validates :bonuses, numericality: { greater_than: -1 }
end

app/controllers/pay_roll_items_controller.rb
class PayRollItemsController < ApplicationController
  before_action :set_pay_roll_item, only: [:show, :edit, :update, :destroy]
  before_action :do_calcs, only: [:update]
  before_action :set_unpayed, only: [:destroy]
  after_action :update_pay_roll, only: [:update]
  after_action :set_payed, only: [:create]
  after_action :set_pay_roll_payed, only: [:create, :update]
   

  # GET /pay_roll_items
  # GET /pay_roll_items.json
  def index
    @pay_roll_items = PayRollItem.all
  end

  # GET /pay_roll_items/1
  # GET /pay_roll_items/1.json
  def show
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /pay_roll_items/new
  def new
    @pay_roll = PayRoll.find(params[:pay_roll_id])
    @pay_roll_item = PayRollItem.new
    @assistances = Assistance.where(assistance_date: @pay_roll.start_date..@pay_roll.end_date).where(
                                        greenhouse_id: @pay_roll.greenhouse_id).where(
                                        pay_roll_item_id: nil)
    @employee_ids = @assistances.where(assisted: true).distinct.pluck(:employee_id)
    @employees = Employee.find(@employee_ids)
  end

  # GET /pay_roll_items/1/edit
  def edit
  end

  # POST /pay_roll_items
  # POST /pay_roll_items.json
  def create
    @pay_roll_item = PayRollItem.new(pay_roll_item_params)

    respond_to do |format|
      if @pay_roll_item.save
        set_total_and_get_assistances
        format.js
        format.html { redirect_to @pay_roll_item.pay_roll, notice: 'Pay roll item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pay_roll_item }
      else
        format.js
        format.html { render action: 'new' }
        format.json { render json: @pay_roll_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pay_roll_items/1
  # PATCH/PUT /pay_roll_items/1.json
  def update
    respond_to do |format|
      if @pay_roll_item.update(pay_roll_item_params)
        format.js
        format.html { redirect_to @pay_roll_item.pay_roll, notice: 'Pay roll item was successfully updated.' }
        format.json { render json: @pay_roll_item }
      else
        format.js
        format.html { render action: 'edit' }
        format.json { render json: @pay_roll_item.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pay_roll_items/1
  # DELETE /pay_roll_items/1.json
  def destroy
    @pay_roll_item.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to pay_roll_items_url }
      format.json { head :no_content }
    end
  end

  def set_payed
    @pay_roll_item.assistances.each do |assistance|
      assistance.payed = true
      assistance.save
    end
  end

  def set_unpayed
    @pay_roll_item.assistances.each do |assistance|
      assistance.payed = false
      assistance.save
      puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11
            assistance.payed = #{assistance.payed}
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1"
    end
  end

  def set_total_and_get_assistances
    @pay_roll = @pay_roll_item.pay_roll
    employee_id = @pay_roll_item.employee_id
    assistances = Assistance.where(assistance_date: @pay_roll.start_date..@pay_roll.end_date).where(employee_id: employee_id).where(pay_roll_item_id: nil)
    @pay_roll_item.assistances = assistances
    @pay_roll_item.save
    @pay_roll_item.total_assistances = @pay_roll_item.assistances.where(assisted: true).count
    @pay_roll_item.save

    @pay_roll_item.total = ((@pay_roll_item.salary * @pay_roll_item.total_assistances) - @pay_roll_item.discounts) + @pay_roll_item.bonuses
    @pay_roll_item.save

    # Update pay_roll
    @pay_roll.subtotal = (@pay_roll.pay_roll_items.sum(:total) + @pay_roll.pay_roll_items.sum(:discounts)) - @pay_roll.pay_roll_items.sum(:bonuses)
    @pay_roll.discount = @pay_roll.pay_roll_items.sum(:discounts)
    @pay_roll.bonus = @pay_roll.pay_roll_items.sum(:bonuses)
    @pay_roll.total = @pay_roll.pay_roll_items.sum(:total)
    @pay_roll.save
  end

  def do_calcs
    # Update discount
    salary = params[:pay_roll_item][:salary].to_f
    discounts = params[:pay_roll_item][:discounts].to_f
    bonuses = params[:pay_roll_item][:bonuses].to_f
    params[:pay_roll_item][:total] = ((@pay_roll_item.total_assistances * salary) - discounts) + bonuses
  end

  def update_pay_roll
    @pay_roll = @pay_roll_item.pay_roll
        
    # Update pay_roll
    @pay_roll.subtotal = (@pay_roll.pay_roll_items.sum(:total) + @pay_roll.pay_roll_items.sum(:discounts)) - @pay_roll.pay_roll_items.sum(:bonuses)
    @pay_roll.discount = @pay_roll.pay_roll_items.sum(:discounts)
    @pay_roll.bonus = @pay_roll.pay_roll_items.sum(:bonuses)
    @pay_roll.total = @pay_roll.pay_roll_items.sum(:total)
    @pay_roll.save
  end

  def update_discount
    respond_to do |format|
      if @pay_roll_item.update(pay_roll_item_params)
        # Update pay_roll_item
        @pay_roll_item.total = ((@pay_roll_item.salary * @pay_roll_item.total_assistances) - @pay_roll_item.discounts) + @pay_roll_item.bonuses
        @pay_roll_item.save
        @pay_roll = @pay_roll_item.pay_roll
        
        # Update pay_roll
        @pay_roll.subtotal = (@pay_roll.pay_roll_items.sum(:total) + @pay_roll.pay_roll_items.sum(:discounts)) - @pay_roll.pay_roll_items.sum(:bonuses)
        @pay_roll.discount = @pay_roll.pay_roll_items.sum(:discounts)
        @pay_roll.bonus = @pay_roll.pay_roll_items.sum(:bonuses)
        @pay_roll.total = @pay_roll.pay_roll_items.sum(:total)
        @pay_roll.save

        format.html { redirect_to @pay_roll_item, notice: 'Pay roll item was successfully updated.' }
        format.json { render json: {:pay_roll_item => @pay_roll_item, 
                                  :pay_roll => @pay_roll }} 
      else
        format.html { render action: 'edit' }
        format.json { render json: @pay_roll_item.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def update_bonus
    respond_to do |format|
      if @pay_roll_item.update(pay_roll_item_params)
        # Update pay_roll_item
        @pay_roll_item.total = ((@pay_roll_item.salary * @pay_roll_item.total_assistances) - @pay_roll_item.discounts) + @pay_roll_item.bonuses
        @pay_roll_item.save
        @pay_roll = @pay_roll_item.pay_roll
        
        # Update pay_roll
        @pay_roll.subtotal = (@pay_roll.pay_roll_items.sum(:total) + @pay_roll.pay_roll_items.sum(:discounts)) - @pay_roll.pay_roll_items.sum(:bonuses)
        @pay_roll.discount = @pay_roll.pay_roll_items.sum(:discounts)
        @pay_roll.bonus = @pay_roll.pay_roll_items.sum(:bonuses)
        @pay_roll.total = @pay_roll.pay_roll_items.sum(:total)
        @pay_roll.save

        format.html { redirect_to @pay_roll_item, notice: 'Pay roll item was successfully updated.' }
        format.json { render json: {:pay_roll_item => @pay_roll_item, 
                                  :pay_roll => @pay_roll } }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pay_roll_item.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def set_pay_roll_payed
    pay_roll = @pay_roll_item.pay_roll
    all_true = true
    pay_roll.pay_roll_items.each do |pay_roll_item|
      all_true = false if pay_roll_item.payed != true
    end
    if all_true == true
      pay_roll.payed = true
      pay_roll.save
    else
      pay_roll.payed = false
      pay_roll.save
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pay_roll_item
      @pay_roll_item = PayRollItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pay_roll_item_params
      params.require(:pay_roll_item).permit(:pay_roll_id, :employee_id, :payed, :salary, :discounts, :bonuses, :total, :assistance_ids)
    end


end

app/helpers/pay_roll_items_helper.rb
module PayRollItemsHelper
end

app/views/pay_roll_items/_create_form.html.erb
<%= simple_form_for(@pay_roll_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.association :pay_roll, :as => :hidden, input_html: { value: @pay_roll.id } %>
  	<%= f.association :employee, label: (t :employee), collection: @employees, label_method: :full_name, value_method: :id %>
  	<%= f.input :salary, label: (t :salary), :input_html => { :value => '0.0' }%>
    <%= f.input :discounts, label: (t :discounts), :input_html => { :value => '0.0' } %>
    <%= f.input :bonuses, label: (t :bonuses), :input_html => { :value => '0.0' } %>
  </div>

  <div class="form-actions">
    <%= f.submit (t :add_employee), class: 'btn btn-default' %>
  </div>
<% end %>
<br>
<%= @assistances.count %>
<%= @employee_ids.count %>
<%= @employees.count %>
<br>

app/views/pay_roll_items/_edit_form.html.erb
<%= simple_form_for(@pay_roll_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :salary, label: (t :salary) %>
    <%= f.input :discounts, label: (t :discounts), :input_html => { :value => '0.0' } %>
    <%= f.input :bonuses, label: (t :bonuses), :input_html => { :value => '0.0' } %>
    <%= f.input :payed, label: (t :payed) %>
  </div>
  <br>

  <div class="form-actions">
    <%= f.submit (t :update), class: "btn btn-default" %>
  </div>
<% end %>
<br><br>

app/views/pay_roll_items/_form.html.erb
<%= simple_form_for(@pay_roll_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :salary %>
    <%= f.input :discounts %>
    <%= f.input :bonuses %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pay_roll_items/_pay_roll_item.html.erb
    <tr  id="pay_roll_item_<%= pay_roll_item.id %>">
            <td><%= pay_roll_item.employee.first_name %></td>
            <td>
              <% pay_roll_item.assistances.each do |assistance| %>
                <%= assistance.assistance_date.strftime('%a') %>
              <% end %>
            </td>
            <td><%= pay_roll_item.total_assistances %></td>
            <td><%= pay_roll_item.salary %></td>
            <td>
              <div class="pay_roll_item_discount_update" id="pay_roll_item_discounts_<%= pay_roll_item.id %>">
                <!-- discounts value -->
                <%= pay_roll_item.discounts %>
              </div>
            </td>
            <td>
              <div class="pay_roll_item_bonus_update" id="pay_roll_item_bonuses_<%= pay_roll_item.id %>">
                <!-- bonuses value -->
                <%= pay_roll_item.bonuses %>
              </div>
            </td>
            <td><div id="pay_roll_item_total_<%= pay_roll_item.id %>"><%= pay_roll_item.total %></div></td>
            <td>
              <div>
                <%= pay_roll_item.payed %>
              </div>
            </td>
            <td><%= link_to 'Destroy', pay_roll_item, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
          </tr>

app/views/pay_roll_items/create.js.erb
//alert('I was called');

//$('div#fertigation_cost').fadeOut();
//$('div#fertigation_cost').text("<%= number_to_currency(@pay_roll_item.pay_roll.total, precision: 2) %>").effect("highlight", {color: '#00DCB7'}, 2000);
$("<%= escape_javascript(render @pay_roll_item) %>").appendTo("#pay_roll_items").effect("highlight", {color: '#00DCB7'}, 2000);
$('#new_pay_roll_item_form')[0].reset();

app/views/pay_roll_items/edit.html.erb
<h1>Editing pay_roll_item</h1>

<%= render 'edit_form' %>

<%= link_to (t :show), @pay_roll_item %> |
<%= link_to (t :back), pay_roll_items_path %>

app/views/pay_roll_items/index.html.erb
<h1>Listing pay_roll_items</h1>

<div class="table-responsive">
  <table class="table table-hover dataTable table-striped table-bordered">
    <thead>
      <tr>
        <th>Id</th>
        <th>Pay roll</th>
        <th>Employee</th>
        <th>Num Assistances</th>
        <th>Salary</th>
        <th>Discounts</th>
        <th>Bonuses</th>
        <th>Total</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @pay_roll_items.each do |pay_roll_item| %>
        <tr>
          <td><%= pay_roll_item.id %></td>
          <td><%= pay_roll_item.pay_roll_id %></td>
          <td><%= pay_roll_item.employee.first_name %></td>
          <td><%= pay_roll_item.total_assistances %></td>
          <td><%= pay_roll_item.salary %></td>
          <td><%= pay_roll_item.discounts %></td>
          <td><%= pay_roll_item.bonuses %></td>
          <td><%= pay_roll_item.total %></td>
          <td><%= link_to 'Show', pay_roll_item %></td>
          <td><%= link_to 'Edit', edit_pay_roll_item_path(pay_roll_item) %></td>
          <td><%= link_to 'Destroy', pay_roll_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Pay roll item', new_pay_roll_item_path %>

app/views/pay_roll_items/new.html.erb
<h1><%=t :add_employee %></h1>
<br>

<%= render 'create_form' %>

<%= link_to 'Back', pay_roll_items_path %>

app/views/pay_roll_items/new.js.erb
$('#new_pay_roll_item_link').hide().after('');

app/views/pay_roll_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pay roll:</strong>
  <%= @pay_roll_item.pay_roll_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @pay_roll_item.employee_id %>
</p>

<p>
  <strong>Assistances:</strong>
  <%= @pay_roll_item.total_assistances %>
</p>

<p>
  <strong>Assistances:</strong>
  <%= @pay_roll_item.assistance_ids %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @pay_roll_item.salary %>
</p>

<p>
  <strong>Discounts:</strong>
  <%= @pay_roll_item.discounts %>
</p>

<p>
  <strong>Bonuses:</strong>
  <%= @pay_roll_item.bonuses %>
</p>

<p>
  <strong>Total:</strong>
  <%= @pay_roll_item.total %>
</p>

<%= link_to 'Edit', edit_pay_roll_item_path(@pay_roll_item) %> |
<%= link_to 'Back', pay_roll_items_path %>

app/views/pay_roll_items/update.js.erb
$('#pay_roll_item_bonuses_' + <%= @pay_roll_item.id %>).fadeOut();
$('#pay_roll_item_bonuses_' + <%= @pay_roll_item.id %>).text(<%= @pay_roll_item.bonuses %>).toFixed(2)).slideDown().effect("highlight", {color: '#00DCB7'}, 2000);
$('#pay_roll_item_total_' + <%= @pay_roll_item.id %>).fadeOut();
$('#pay_roll_item_total_' + <%= @pay_roll_item.id %>).text(<%= @pay_roll_item.total %>).toFixed(2)).slideDown().effect("highlight", {color: '#00DCB7'}, 2000);