config/routes.rb
Myapp::Application.routes.draw do

  resources :accounts
  resources :plans
  get 'static_pages/index'

  get 'steps/first'

  get 'steps/second'

  get 'steps/third'

  get 'steps/fourth'

  get 'steps/finish'

  resources :events
  resources :receipes
  resources :apportionment_per_greenhouses
  resources :user_roles
  resources :permissions
  resources :roles
  resources :role_permissions
  resources :user_companies
  resources :cycles
  resources :companies
  
  get 'reports/index'

  get 'reports/quick_general_status'

  resources :unit_conversions
  resources :unit_types
  resources :selections
  resources :product_varieties
  resources :product_presentations
  resources :product_qualities
  resources :selection_items
  resources :sales
  resources :sale_items
  resources :products
  resources :harvests
  resources :weathers
  resources :environments
  resources :environmental_conditions
  resources :phenological_stages
  resources :leachates
  resources :suppliers
  resources :product_application_buys
  resources :administration_costs
  resources :operating_costs
  resources :fertigations
  resources :fertigation_items
  resources :application_products
  resources :application_items
  resources :applications
  resources :application_processes
  resources :greenhouse_employees

  resources :pay_roll_items do
    put :update_discount
    put :update_bonus
  end

  resources :pay_rolls

  resources :assistances

  resources :job_positions

  resources :greenhouses

  resources :employees

  get "home/index"
  get "home/minor"

  devise_for :users, controllers: { registrations: "users/registrations", 
                                    sessions: "users/sessions" }

  devise_scope :user do 
    get "users_list" => "manage_users#index"
    get "edit_user" => "manage_users#edit_user"
    get "new_user" => "manage_users#new_user"
    post "create_user" => "manage_users#create_user"
    post "update_user" => "manage_users#update_user"
    get "show_user" => "manage_users#show_user"
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

root to: 'static_pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :product_varieties
	has_many :product_presentations
	has_many :product_qualities
	has_many :harvests
	has_many :sales
	has_many :selections
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :greenhouse
	belongs_to :product_variety
	belongs_to :product_presentation
	belongs_to :product
	has_many :sale_items

	validates :event_date, :greenhouse, :product, :product_variety, :product_presentation, presence: true

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    @sale = Sale.new
    if params[:search]
      company_id = params[:search][:company_id]
      greenhouse_id = params[:search][:greenhouse_id]
      @show_sales = true
      @greenhouse = Greenhouse.find(greenhouse_id)
      @cycle = Cycle.where(greenhouse_id: greenhouse_id).active.first
      from_date = @cycle.start_date
      to_date = @cycle.end_date
      @sales = Sale.where(greenhouse_id: greenhouse_id).where(event_date: from_date..to_date).order(:event_date)
      @sale = Sale.new
    else
      @show_sales == false
      @companies = current_user.companies
      @greenhouses = Greenhouse.where(company_id: @companies.first.id..@companies.last.id)
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale_items = @sale.sale_items
    @sale_item = SaleItem.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.js
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.js
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:event_date, :product_id, :product_variety_id, :product_presentation_id, 
        :total_price, :status, :greenhouse_id, :sale_item_ids)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :event_date %>
    <%= f.association :product %>
    <%= f.association :product_variety %>
    <%= f.association :product_presentation %>
    <%= f.input :total_price %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
	  <tr id="sale_<%= sale.id %>">
        <td><%= sale.event_date %></td>
        <td><%= sale.greenhouse.name %></td>
        <td><%= sale.product.name %></td>
        <td><%= sale.product_variety.name %></td>
        <td><%= sale.product_presentation.name %></td>
        <td>
            <div class="table-responsive">
                <table class="table table-hover dataTable table-striped table-bordered">
                    <thead>
                        <tr>
                            <% @product_quality_ids = sale.sale_items.order(:product_quality_id).pluck(:product_quality_id).uniq %>
                            <% @product_quality_ids.each do |product_quality_id| %>
                                <% @product_quality = ProductQuality.find(product_quality_id) %>
                                <td><strong><%= @product_quality.name %></strong></td>
                            <% end %>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <% @product_quality_ids.each do |product_quality_id| %>
                                <% @product_quality = ProductQuality.find(product_quality_id) %>
                                    <td><%= sale.sale_items.where(product_quality_id: product_quality_id).sum(:quantity) %></td>
                            <% end %>
                        </tr>
                    </tbody>
                </table>
            </div>
            <strong>
                <%=t :total_quantity %>: <%= number_with_precision(sale.sale_items.sum(:quantity), precision: 0, delimiter: ',') %>
            </strong>
        </td>
        <td style="text-align: right;">
            <strong>
                <%= number_to_currency(sale.total_price, precision: 2) %>
            </strong>
        </td>
        <td><%= sale.status %></td>
        <td><%= link_to (t :show), sale %></td>
        <td><%= link_to (t :destroy), sale, method: :delete, remote: true, data: { confirm: (t :are_you_sure) } %></td>
      </tr>

app/views/sales/_sale_item.html.erb
	  <tr id="sale_item_<%= sale_item.id %>">
        <td><%= sale_item.product_quality.name %></td>
        <td><%= sale_item.quantity %></td>
        <td><%= sale_item.unit_price %></td>
        <td><%= sale_item.total_price %></td>
        <td><%= sale_item.status %></td>
        <td><%= link_to (t :destroy), sale_item, method: :delete, remote: true, data: { confirm: (t :are_you_sure) } %></td>
      </tr>

app/views/sales/create.js.erb
//alert('I was called');
$("<%= escape_javascript(render @sale) %>").appendTo("#sales").effect("highlight", {color: '#00DCB7'}, 2000);
$('#new_sale_form')[0].reset();

app/views/sales/destroy.js.erb
//alert('Hola');
$('#<%= dom_id(@sale) %>').effect("highlight", {color: '#00DCB7'}, 800).fadeOut();

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<% if @show_sales == true  %>
  <h1><%=t :sales %></h1>

  <div class="table-responsive">
    <table class="table table-hover dataTable table-striped table-bordered">
      <thead>
        <tr>
          <th><%=t :event_date %></th>
          <th><%=t :greenhouse %></th>
          <th><%=t :product %></th>
          <th><%=t :product_variety %></th>
          <th><%=t :product_presentation %></th> 
          <th><%=t :sales %></th>
          <th><%=t :total_price %></th>
          <th><%=t :status %></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody id="sales">
        <% @sales.each do |sale| %>
          <%= render "sale", :sale => sale %>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <div class="col-md-8">
  <br>
  <br>
    <strong><%=t :total_sold %>:  <%= number_to_currency(@sales.sum(:total_price), precision: 2) %></strong>
  </div>

  <div class="col-md-8">
  <br>
  <br>
  <br>
    <%= link_to (t :new_sale), new_sale_path, remote: true, id: 'new_sale_link' %>
  </div>


  <br>
  <div class="col-md-5" id="div_new_sale_form">
    <%= simple_form_for(@sale, remote: true, html: { id: 'new_sale_from' }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :event_date, label: (t :event_date) %>
        <%= f.association :greenhouse, :as => :hidden, input_html: { value: @greenhouse.id } %>
        <%= f.association :product, label: (t :product) %>
        <%= f.association :product_variety, label: (t :product_variety) %>
        <%= f.association :product_presentation, label: (t :product_presentation) %>
      </div>

      <div class="form-actions">
        <%= f.submit (t :create_sale), id: 'new_sale_submit_button', class: 'btn btn-default' %>
      </div>
    <% end %>

  </div>

<% else %>
  <div class="col-md-2">
    <%= simple_form_for :search, url: sales_path, :method => :get do |f| %>
        <%= f.input :company_id, collection: @companies, label_method: :name, value_method: :id, placeholder: 'Select the company' %>
        <%= f.input :greenhouse_id, collection: @greenhouses, label_method: :name, value_method: :id, placeholder: 'Select the company' %>
        <%= f.submit 'Generar', class: 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/new.js.erb
$('#new_sale_link').hide().after('');

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-8">
  <div class="col-md-4">
    <strong><%=t :event_date %>:</strong>
    <%= @sale.event_date %>
  </div>

  <div class="col-md-4">
    <strong><%=t :product %>:</strong>
    <%= @sale.product.name %>
  </div>
</div>

<div class="col-md-8">
  <div class="col-md-4">
    <strong><%=t :product_variety %>:</strong>
    <%= @sale.product_variety.name %>
  </div>

  <div class="col-md-4">
    <strong><%=t :product_presentation %>:</strong>
    <%= @sale.product_presentation.name %>
  </div>
</div>

<div class="col-md-8">
  <div class="col-md-4">
    <strong><%=t :status %>:</strong>
    <%= @sale.status %>
  </div>
</div>

<div class="col-md-8">
    <div class="table-responsive">
      <table class="table table-hover dataTable table-striped table-bordered">
        <thead>
          <tr>
            <th><%=t :product_quality %></th>
            <th><%=t :quantity %></th>
            <th><%=t :unit_price %></th>
            <th><%=t :total_price %></th>
            <th><%=t :status %></th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody id="sale_items"  data-turbolinks-temporary>
          <% @sale_items.each do |sale_item| %>
            <%= render "sale_item", :sale_item => sale_item %>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>


    <div class="col-md-8">
      <%= link_to (t :add), new_sale_item_path, remote: true, id: 'new_sale_item_link' %>
      <br>
      <br>
    </div>


    <br>
    <div class="col-md-5" id="div_new_sale_item_form">
      <%= simple_form_for(@sale_item, remote: true, html: { id: 'new_sale_item_from' }) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.association :sale, :as => :hidden, input_html: { value: @sale.id } %>
          <%= f.association :product_quality, label: (t :product_quality) %>
          <%= f.input :quantity, label: (t :quantity) %>
          <%= f.input :unit_price, label: (t :unit_price) %>
          <%= f.input :status, collection: [(t :payed), (:credit)] %>
        </div>

        <div class="form-actions">
          <%= f.submit (t :add), id: 'new_sale_item_submit_button', class: 'btn btn-default' %>
          <br>
          <br>
        </div>
      <% end %>

    </div>
</div>

<div class="col-md-8">
  <div class="col-md-4">
    <strong><%=t :total_price %>:</strong>
    <div id="sale_total_price"><%= @sale.total_price %></div>
  </div>
</div>



<div class="col-md-8">
  <br>
  <br>
  <br>
  <br>
  <%= link_to (t :edit), edit_sale_path(@sale) %> |
  <%= link_to (t :back), sales_path %>
</div>